


spring.application.name=sb-ecom

# ==========================================
# DATABASE CONFIGURATION (PostgreSQL)
# ==========================================
spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecommerce}
spring.datasource.username=${DATASOURCE_USER:postgres}
spring.datasource.password=${DATASOURCE_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Uses 'update' locally, but you MUST set DB_DDL_AUTO=validate in Railway!
spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:update}


FRONTEND_URL=https://zappit.online
frontend.url=${FRONTEND_URL:https://zappit.online}

image.base.url=${IMAGE_BASE_URL:http://localhost:8080/images}
project.image=images/


# Provide a dummy string for local testing so it doesn't crash
spring.app.jwtSecret=${JWT_SECRET}
spring.app.jwtExpirationMs=30000000
spring.ecom.app.jwtCookieName=ecom-cookie

# Admin Credentials
app.admin.email=${ADMIN_EMAIL:admin1@example.com}
app.admin.password=${ADMIN_PASSWORD:dummyPassword}


razorpay.key.id=${RAZOR_ID}
razorpay.key.secret=${RAZOR_SECRET_KEY}



spring.security.oauth2.client.registration.google.client-id=${OAUTH_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${OAUTH_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}



brevo.api.key=${BREVO_API_KEY}
spring.mail.from=${MAIL_FROM:noreply@zappit.online}



# ==========================================
# LOGGING (Keep DEBUG for local, INFO for Prod)
# ==========================================
logging.level.org.springframework=${LOG_LEVEL:DEBUG}
logging.level.org.hibernate.SQL=${LOG_LEVEL:DEBUG}
logging.level.org.springframework.security=${LOG_LEVEL:DEBUG}
logging.level.com.ecommerce.project=${LOG_LEVEL:DEBUG}


spring.config.import=optional:file:.env


# Cloudinary Credentials (We use variables so we can hide them on Render later)
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Increase Spring Boot Upload Limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Tell Spring Boot it is running behind a proxy (Render) so it uses HTTPS for OAuth redirects instead of HTTP
server.forward-headers-strategy=framework
